### ISSUE TITLE
Mentions in replies.

### ISSUE THREAD

**Issue by FredericJacobs** [beccadax/appnetkit#2]
Hi,

Currently the mentioning system is really poor. 

Two improvements should be made :

1) When I reply to a post that's mentioning several users I would like to mention everyone 

2) I should never, ever, be able to mention myself.

Any thoughts on that ?

**Comment by beccadax** [comment]
2 would be lovely, but is impossible to do completely automatically. The problem is that ANSession doesn't necessarily automatically know which user it's logged in as; you have to run `-accessTokenInformationWithCompletion:` to find out, and since that method takes a completion handler, `-replyDraft` would have to as well.

1 is sometimes, but not always, what you want.

What I may do is add a `-replyDraftToAllExceptUser:` method, which takes a user to exclude. You would have to look up the current user yourself and pass it in, but the effect would be the same. Would that do what you want?

(And do note that if you don't like how AppNetKit is generating drafts for you, you can always modify the returned drafts, or even create your own drafts from scratch. `-replyDraft` and its ilk are handy shortcuts, not suicide pacts.)

**Comment by FredericJacobs** [comment]
Yeah I would love -replyDraftToAllExceptUser: 

That would be awesome.

It would be great if the user I'm replying to is the first mention in the text when there are many

**Comment by beccadax** [comment]
The method you asked for, as well as one that operates on raw usernames, has been added as of commit 9a048ee5a04000e13fbd2162d892df874cce4998. (Note that it _does_ mention yourself if you're directly replying to one of your own posts; I've seen this style used on Twitter when a person is correcting himself or answering his own question.) Let me know if you have any trouble with it.

**Comment by FredericJacobs** [comment]
-[__NSCFString appNetUsernameString]: unrecognized selector sent to instance 0x769fe10 keeps crashing

**Comment by beccadax** [comment]
@FredericJacobs A couple suggestions:
1. Make sure your project includes the new NSString+AppNetExtensions.m file.
2. If you're building AppNetKit as a static library and then linking that into your project, you may need to use the -ObjC and possibly -all_load linker flags. More details: http://stackoverflow.com/questions/2567498/objective-c-categories-in-static-library

**Comment by FredericJacobs** [comment]
My bad. But you forgot the "@" symbol for the first mention

**Comment by beccadax** [comment]
@FredericJacobs Thanks for reporting that—it's fixed as of cfd09d3969aef26bbc5b6693aacba2e4321775d1.
